header:
    title: New Age Autonomous Inspection!
    text: Enhancing Industrial Automation
    button: Tell Me More
    buttonlink: "#services"

services:
    title: "Services"
    text: "Automated Inspection"
    section: services
    list:
      - title: "Equipment and Industrial Machinery"
        desc: "Using scalable technologies to develop hardware and software which is both economical and easy to use."
        icon: fas fa-magic #find more at https://fontawesome.com/icons
      - title: "Computer Vision"
        desc: "Automate surface visual inspection on product lines to ensure maximum productivity and quality in manufacturing."
        icon: fas fa-laptop       
      - title: "Customer Service and Training"
        desc: "Make product lines faster by smartly using robotics"
        icon: fas fa-hands-helping

    

timeline:
    title: "About" 
    #text: "Lorem ipsum timeline"
    #section: timeline
    # left is the default
    #start_align: "left"
    events:
      - title: "Our Humble Beginnings"
        year: "2020-Present"
        desc: "Our approach is to provide surface visual inspection at nominal cost using expertise and innovative technologies."
        image: assets/img/timeline/1.jpg
        alt:
        # you can enforce the aligment
        align: right
    end: "Be Part <br> of Our <br> Story!"

about:
    title: "About Us"
    text: "our story"
    section: about

clients:
    section: clients
    max-height: 100px
    horizontal-scrolling: "" #"yes/no"
    list:
      - title: "Startup India"
        url: https://www.startupindia.gov.in/
        logo: https://upload.wikimedia.org/wikipedia/en/9/9d/Startup_India_logo.png
      - title: "Dite IIF"
        url:  https://www.diteiif.com/home
        logo: https://www.diteiif.com/img/img001.png
      - title: "Make in India"
        url: https://www.makeinindia.com/
        logo: https://www.makeinindia.com/themes/bootstrap4/images/slider-img-1.png
      - title: "Digital India"
        url: https://www.digitalindia.gov.in
        logo: https://digitalindia.gov.in/writereaddata/files/Headerlogo_0.png
    
team:
    title: "OUR AMAZING TEAM"
    #text: "Lorem ipsum dolor sit amet consectetur."
    #subtext: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde. **Markdown** supported.
    section: team
    people:
      - name: "Anshuman Fauzdar"
        role: "CMD"
        image: https://miro.medium.com/fit/c/262/262/1*aYVVhYMmnxUziznwIYmDPA.jpeg # https://avatars.githubusercontent.com/u/40523329?s=96&v=4
        social:
          - url: https://twitter.com/anshumanfauzdar
            icon: fab fa-twitter
          - url: https://github.com/AnshumanFauzdar
            icon: fab fa-github
          - url: https://www.linkedin.com/in/anshumanfauzdar/
            icon: fab fa-linkedin-in
      - name: "Prateek Jindal"
        role: "Finance Head"
        image: https://avatars.githubusercontent.com/u/51196145?s=96&v=4
        social:
#          - url: https://twitter.com
#            icon: fab fa-twitter
          - url: https://github.com/Pra-xo
            icon: fab fa-github
#          - url: https://linkedin.com
#            icon: fab fa-linkedin-in
      - name: "Akshay Goyal"
        role: "CEO"
        image: assets/img/team/akshay.jpeg # https://avatars.githubusercontent.com/u/65530323?s=96&v=4
        social:
#          - url: https://twitter.com
#            icon: fab fa-twitter
          - url: https://github.com/scorpiangoyal121
            icon: fab fa-github
#          - url: https://linkedin.com
#            icon: fab fa-linkedin-in
      - name: "Shubham Rajput"
        role: "Technical Head"
        image: https://avatars.githubusercontent.com/u/52489868?s=96&v=4
        social:
#          - url: https://twitter.com
#            icon: fab fa-twitter
          - url: https://github.com/Shubham0Rajput
            icon: fab fa-github
#          - url: https://linkedin.com
#            icon: fab fa-linkedin-in
      - name: "Sunny Vedwal"
        role: "Administration"
        image: https://avatars.githubusercontent.com/u/51956566?s=96&v=4
        social:
#          - url: https://twitter.com
#            icon: fab fa-twitter
          - url: https://github.com/sunnyvedwal
            icon: fab fa-github
#          - url: https://linkedin.com
#            icon: fab fa-linkedin-in
      - name: "Vinay Dhiman"
        role: "Public Relations"
        image: https://avatars.githubusercontent.com/u/65610858?s=400
        social:
#          - url: https://twitter.com
#            icon: fab fa-twitter
          - url: https://github.com/VinayDhiman
            icon: fab fa-github
#          - url: https://linkedin.com
#            icon: fab fa-linkedin-in
      - name: "Vinayak Verma"
        role: "HR"
        image: https://avatars.githubusercontent.com/u/38384489?s=96&v=4
        social:
#          - url: https://twitter.com
#            icon: fab fa-twitter
          - url: https://github.com/V-kage
            icon: fab fa-github
#          - url: https://linkedin.com
#            icon: fab fa-linkedin-in 

contact:
    title: "Contact Us"
    text: "reach us at SwayattDrishtigochar@gmail.com"
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
#      - url: https://twitter.com
#        icon: "fab fa-twitter"  
#      - url: https://facebook.com
#        icon: "fab fa-github"
      - url: https://www.linkedin.com/company/swayattdrishtigochar/
        icon: "fab fa-linkedin-in"
      - url: https://github.com/SwayattDrishtigochar
        icon: "fab fa-github"
#      - url: https://instagram.com
#        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
